name: TokenUs

version: '3.8'

networks:
  app-network: # 사용자 정의 네트워크
    driver: bridge

services:
  mysql:
    container_name: tokenus-mysql
    image: mysql:latest
    ports:
      - 3307:3306
    restart: always
    networks:
      - app-network # 사용자 정의 네트워크에 연결
    volumes:
      - ./data/tokenus-mysql:/var/lib/mysql # Docker 볼륨 사용, 로컬 경로 매핑
      - ./logs/tokenus-mysql:/var/log/mysql #로그 관리 Volume
    env_file: ./env/local-db.env