#spring.application.name=TokenUs_BE
#DB Setting

spring:
  application:
    name: tokenus

  config:
    import:
      - optional:file:env/local.env[.properties]

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: ${MYSQL_DRIVER}
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true #실행되는 SQL을 콘솔에 출력
    properties:
      hibernate:
        format_sql: true #SQL을 보기 좋게 포맷팅하여 출력
        use_sql_comments: true #SQL 실행시 주석 표시
        hbm2ddl.auto: update #DB 테이블 자동 업데이트(개발환경에서만, 서버에서는 none)
        default_batch_fetch_size: 1000 # 성능 최적화를 위한 배치 크기 설정
        time_zone: KST

logging:
  level:
    com.example: debug
jwt:
  secret: ${JWT_SECRET}