#spring.application.name=TokenUs_BE
#DB Setting

spring:
  main:
    lazy-initialization: true
  application:
    name: tokenus
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: ${MYSQL_DRIVER}
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        hbm2ddl.auto: create
        default_batch_fetch_size: 1000
        time_zone: KST

logging:
  level:
    org.springframework.security: DEBUG
    TokenUs.TokenUs_BE: DEBUG

jwt:
  secret: ${JWT_SECRET}

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    bucket-name: ${AWS_S3_BUCKET}
    region: ${AWS_DEFAULT_REGION}

web3:
  rpc-url: ${RPC_URL}
  videonft-contract-address: ${VIDEO_NFT_CONTRACT_ADDRESS}
  marketplace-contract-address: ${MARKET_PLACE_CONTRACT_ADDRESS}
  private-key: ${PRIVATE_KEY}

flask:
  url: ${FLASK_URL}
