#!/bin/bash

echo "Use spotless to format code..."

# Spotless apply
if ./gradlew spotlessApply; then

    # Restaging files after Spotless apply
    git diff --staged --name-only | while read -r file; do
        [ -f "$file" ] && git add "$file"
    done

else
    echo "Spotless 자동 포맷팅에 실패했습니다." >&2
    exit 1
fi
