name: tokenus

services:
  tokenus-mysql:
    container_name: tokenus-mysql
    image: mysql:latest
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - tokenus-network
    command: [ "--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci" ] # MySQL 서버가 실행될 때 사용할 문자셋 및 정렬 규칙 지정
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tokenus-app:
    container_name: tokenus-app
    image: ${APP_IMAGE}
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - tokenus-network
    restart: always
    depends_on:
      tokenus-mysql:
        condition: service_healthy  # MySQL이 완전히 실행된 후 Spring Boot 실행
    cpus: "0.5"           # ✅ CPU 사용 제한
    mem_limit: 512m       # ✅ 메모리 사용 제한 (512MB)

networks:
  tokenus-network:
    external: true

volumes:
  mysql_data: